import {
  // Authentication & User Management
  REGISTER_URL,
  LOGIN_URL,
  LOGOUT_URL,
  VERIFY_TOKEN_URL,
  CHANGE_PASSWORD_URL,
  RESEND_EMAIL_URL,
  RESET_PASSWORD_URL,
  PASSWORD_RESET_CONFIRM_URL,
  REFRESH_TOKEN_URL,
  USER_URL,
  MASS_REGISTER_URL,

  // Attendance Management
  ATTENDANCE_SESSION_URL,
  ATTENDANCE_RECORD_URL,
  BORROW_ACCOUNT_URL,
  FACIAL_RECOGNITION_DATA_URL,
  BORROWED_ATTENDANCE_RECORD_URL,

  // Course Management
  COURSE_URL,
  COURSE_ENROLLMENTS,
  COURSE_ATTENDANCE_SETTINGS,
  COURSE_STUDENTS,

  // School Management
  SCHOOL_URL,
  DEPARTMENT_URL,
  PROGRAM_URL,
  CLASS_GROUPS_URL,
  SEMESTER_URL,
  ACADEMIC_YEAR_URL,

  // Timetable Management
  TIMETABLE_URL,
  EXAM_TIMETABLE_URL,
  TIMETABLE_SLOTS_URL,
  TIMETABLE_CONFLICTS_URL,

  // Configuration & Settings
  SYSTEM_SETTINGS_URL,
  CAT_ATTENDANCE_WEEK_URL,
  TIMETABLE_RULE_URL,
  AUDIT_LOG_URL,

  // Geolocation
  GEOLOCATION_ZONE_URL,
  GEOLOCATION_LOGS_URL,
  GEOLOCATION_SETTINGS_URL,

  // Reporting
  ATTENDANCE_REPORT_URL,
  STUDENT_ATTENDANCE_HISTORY_URL,
  TIMETABLE_ADHERENCE_URL,
  ATTENDANCE_ANALYTICS_URL,
  COURSE_ANALYTICS_URL,
  STUDENT_ANALYTICS_URL,
  EXPORT_ATTENDANCE_REPORT_URL,
  EXPORT_COURSE_REPORT_URL,
  EXPORT_STUDENT_REPORT_URL,

  // Dashboard
  ADMIN_DASHBOARD_STATS_URL,
  ADMIN_DASHBOARD_ANALYTICS_URL,
  LECTURER_DASHBOARD_STATS_URL,
  LECTURER_COURSES_URL,
  STUDENT_DASHBOARD_STATS_URL,
  STUDENT_COURSES_URL,
  HOD_DASHBOARD_STATS_URL,
  DEPARTMENT_ANALYTICS_URL,
  DEAN_DASHBOARD_STATS_URL,
  SCHOOL_ANALYTICS_URL,
} from './apiConfig';

class ApiService {
  // Authentication & User Management
  static REGISTER_URL = REGISTER_URL;
  static LOGIN_URL = LOGIN_URL;
  static LOGOUT_URL = LOGOUT_URL;
  static VERIFY_TOKEN_URL = VERIFY_TOKEN_URL;
  static CHANGE_PASSWORD_URL = CHANGE_PASSWORD_URL;
  static RESEND_EMAIL_URL = RESEND_EMAIL_URL;
  static RESET_PASSWORD_URL = RESET_PASSWORD_URL;
  static PASSWORD_RESET_CONFIRM_URL = PASSWORD_RESET_CONFIRM_URL;
  static REFRESH_TOKEN_URL = REFRESH_TOKEN_URL;
  static USER_URL = USER_URL;
  static MASS_REGISTER_URL = MASS_REGISTER_URL;

  // Attendance Management
  static ATTENDANCE_SESSION_URL = ATTENDANCE_SESSION_URL;
  static ATTENDANCE_RECORD_URL = ATTENDANCE_RECORD_URL;
  static BORROW_ACCOUNT_URL = BORROW_ACCOUNT_URL;
  static FACIAL_RECOGNITION_DATA_URL = FACIAL_RECOGNITION_DATA_URL;
  static BORROWED_ATTENDANCE_RECORD_URL = BORROWED_ATTENDANCE_RECORD_URL;

  // Course Management
  static COURSE_URL = COURSE_URL;
  static COURSE_ENROLLMENTS = COURSE_ENROLLMENTS;
  static COURSE_ATTENDANCE_SETTINGS = COURSE_ATTENDANCE_SETTINGS;
  static COURSE_STUDENTS = COURSE_STUDENTS;

  // School Management
  static SCHOOL_URL = SCHOOL_URL;
  static DEPARTMENT_URL = DEPARTMENT_URL;
  static PROGRAM_URL = PROGRAM_URL;
  static CLASS_GROUPS_URL = CLASS_GROUPS_URL;
  static SEMESTER_URL = SEMESTER_URL;
  static ACADEMIC_YEAR_URL = ACADEMIC_YEAR_URL;

  // Timetable Management
  static TIMETABLE_URL = TIMETABLE_URL;
  static EXAM_TIMETABLE_URL = EXAM_TIMETABLE_URL;
  static TIMETABLE_SLOTS_URL = TIMETABLE_SLOTS_URL;
  static TIMETABLE_CONFLICTS_URL = TIMETABLE_CONFLICTS_URL;

  // Configuration & Settings
  static SYSTEM_SETTINGS_URL = SYSTEM_SETTINGS_URL;
  static CAT_ATTENDANCE_WEEK_URL = CAT_ATTENDANCE_WEEK_URL;
  static TIMETABLE_RULE_URL = TIMETABLE_RULE_URL;
  static AUDIT_LOG_URL = AUDIT_LOG_URL;

  // Geolocation
  static GEOLOCATION_ZONE_URL = GEOLOCATION_ZONE_URL;
  static GEOLOCATION_LOGS_URL = GEOLOCATION_LOGS_URL;
  static GEOLOCATION_SETTINGS_URL = GEOLOCATION_SETTINGS_URL;

  // Reporting
  static ATTENDANCE_REPORT_URL = ATTENDANCE_REPORT_URL;
  static STUDENT_ATTENDANCE_HISTORY_URL = STUDENT_ATTENDANCE_HISTORY_URL;
  static TIMETABLE_ADHERENCE_URL = TIMETABLE_ADHERENCE_URL;
  static ATTENDANCE_ANALYTICS_URL = ATTENDANCE_ANALYTICS_URL;
  static COURSE_ANALYTICS_URL = COURSE_ANALYTICS_URL;
  static STUDENT_ANALYTICS_URL = STUDENT_ANALYTICS_URL;
  static EXPORT_ATTENDANCE_REPORT_URL = EXPORT_ATTENDANCE_REPORT_URL;
  static EXPORT_COURSE_REPORT_URL = EXPORT_COURSE_REPORT_URL;
  static EXPORT_STUDENT_REPORT_URL = EXPORT_STUDENT_REPORT_URL;

  // Dashboard
  static ADMIN_DASHBOARD_STATS_URL = ADMIN_DASHBOARD_STATS_URL;
  static ADMIN_DASHBOARD_ANALYTICS_URL = ADMIN_DASHBOARD_ANALYTICS_URL;
  static LECTURER_DASHBOARD_STATS_URL = LECTURER_DASHBOARD_STATS_URL;
  static LECTURER_COURSES_URL = LECTURER_COURSES_URL;
  static STUDENT_DASHBOARD_STATS_URL = STUDENT_DASHBOARD_STATS_URL;
  static STUDENT_COURSES_URL = STUDENT_COURSES_URL;
  static HOD_DASHBOARD_STATS_URL = HOD_DASHBOARD_STATS_URL;
  static DEPARTMENT_ANALYTICS_URL = DEPARTMENT_ANALYTICS_URL;
  static DEAN_DASHBOARD_STATS_URL = DEAN_DASHBOARD_STATS_URL;
  static SCHOOL_ANALYTICS_URL = SCHOOL_ANALYTICS_URL;
}

export default ApiService;
